version: "3.8"
services:
  frontend:
    container_name: wanderlust-frontend
    build: ./frontend
    ports:
      - 5173:5173
  backend:
    container_name: wanderlust-backend
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    container_name: wanderlust-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./backend/data:/data/db

volumes:
  data: